### ISSUE TITLE
Turret Mech

### ISSUE THREAD

**Issue by benjamin-antupit** [Gryphon-Robotics-4990/2019#22]
- [x] Add Talon for turret turning
- [x] Add software for 359º stop 
    - [x] 3 Hall effects sensors
    - [x] An encoder on versa planetary of turret motor?
- [x] Add joystick input
    - [x] Maybe use bumpers on back of the controller? One to turn left, the other right?
    - [x] Add setpoints as buttons
        - [x] **forward**
        - [x] **left**
        - [x] **right**
        - [x] **back**
        - [x] **safe state (45º back)**
     - [x] ~~Maybe use the POV pad?~~
- [x] Add reset function. How do we zero it?
- [x] **put important data on the dashboard**

**Comment by MajikalExplosions** [comment]
@yellowjaguar5 is done.
