### ISSUE TITLE
Hatch grabber mech

### ISSUE THREAD

**Issue by benjamin-antupit** [Gryphon-Robotics-4990/2019#23]
- [x] Add pneumatic piston
    - [x] Add button
- [x] Add [KOP seat motor](http://wpilib.screenstepslive.com/s/4485/m/63630/l/679357-bosch-seat-motor)
    - [x] Add talon
    - [x] Add [DIO](https://www.andymark.com/products/bosch-seat-motor-dio-kit). [(more info)](https://www.chiefdelphi.com/t/java-code-for-bosch-seat-motor-with-dio-kit/164325/4?u=benjamina)
      Note: 1 pinion (output shaft) rotation = 174.9 encoder rotations  
    - [x] Add counter thing so that we can create setpoints
- [x] Add setpoints at 
    - [x] 0º (out to grab hatch)
    - [x] 90º (holding hatch)
    - [x] **add comand that toggles between the two**
- [x] Add reset function. How do we zero it?
- [x] **put important data on the dashboard**

**Comment by MajikalExplosions** [comment]
@yellowjaguar5 this is done for now (until the limit switches come in or something)
