### ISSUE TITLE
Limelight 

### ISSUE THREAD

**Issue by MajikalExplosions** [Gryphon-Robotics-4990/2019#24]
- [x] **start a command for targeting with limelight**
- [x] Pipeline tuning: http://docs.limelightvision.io/en/latest/vision_pipeline_tuning.html#
- [ ] Crosshair calibration: http://docs.limelightvision.io/en/latest/crosshair_calibration.html
- [x] Estimating distance: http://docs.limelightvision.io/en/latest/cs_estimating_distance.html
- [x] Aiming using vision: http://docs.limelightvision.io/en/latest/cs_aiming.html
- [ ] More advanced stuff: http://docs.limelightvision.io/en/latest/cs_aimandrange.html
- [x] ???
- [ ] Profit

**Comment by MajikalExplosions** [comment]
Can't do until vision tape arrives :(

**Comment by benjamin-antupit** [comment]
- [x] **start a command for targeting with limelight**

**Comment by benjamin-antupit** [comment]
@MajikalExplosions Vision tape arrived.
